/**
 * JetKur Cloudflare Worker Script Template (Sprint 16.2)
 *
 * Worker Target: "jetkur-customer-sites"
 * Production Workers.dev URL: "https://jetkur-customer-sites.selimoyan.workers.dev"
 *
 * Architectural Invariants:
 * 1. Zero dynamic database lookup during visitor request (0 PostgreSQL / 0 Node hits).
 * 2. Static Assets first: uses env.ASSETS binding for native high-performance edge caching.
 * 3. Exact routing resolution: Hostname -> Routing Manifest -> sites/<siteId>/v<version>/<path>.
 * 4. Dedicated workers.dev fallback: serves configured demo site (e.g. demo.jetkur.com.tr)
 *    when directly accessed via jetkur-customer-sites.selimoyan.workers.dev for smoke verification.
 * 5. Unknown hostname returns clean 404 (prevents tenant cross-contamination).
 */

export const WORKER_NAME = "jetkur-customer-sites";
export const WORKERS_DEV_HOSTNAME = "jetkur-customer-sites.selimoyan.workers.dev";
export const DEFAULT_DEMO_SITE_ID = "site-demo-kadikoy";

/**
 * Generates the production ES Module Worker code
 * Embeds the current routing manifest and wires env.ASSETS
 */
export function generateCloudflareWorkerScript(
  embeddedRoutingManifestJson: string,
  demoSiteId = DEFAULT_DEMO_SITE_ID
): string {
  return `/**
 * JetKur Shared Customer Sites Worker (Auto-generated by JetKur Control Plane)
 * Worker Name: ${WORKER_NAME}
 */

// Edge-embedded routing manifest (O(1) resolution, 0 DB roundtrips)
const ROUTING_MANIFEST = ${embeddedRoutingManifestJson};
const WORKERS_DEV_HOST = "${WORKERS_DEV_HOSTNAME}";
const DEFAULT_DEMO_SITE_ID = "${demoSiteId}";

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    const hostHeader = request.headers.get("host") || url.hostname;
    const cleanHost = hostHeader.split(":")[0].toLowerCase().trim();

    // 1. Resolve hostname in routing manifest
    let route = ROUTING_MANIFEST[cleanHost];

    // Reciprocal www / apex fallback
    if (!route) {
      if (cleanHost.startsWith("www.")) {
        route = ROUTING_MANIFEST[cleanHost.replace(/^www\\./, "")];
      } else {
        route = ROUTING_MANIFEST["www." + cleanHost];
      }
    }

    // Special test mode: direct access via jetkur-customer-sites.selimoyan.workers.dev
    if (!route && (cleanHost === WORKERS_DEV_HOST || cleanHost.endsWith(".workers.dev"))) {
      // Look for demo site or first active route in manifest
      route = Object.values(ROUTING_MANIFEST).find(r => r.siteId === DEFAULT_DEMO_SITE_ID) || Object.values(ROUTING_MANIFEST)[0];
    }

    // Unknown hostname: return safe 404 (do not leak another customer's site)
    if (!route) {
      return new Response(
        "<!DOCTYPE html><html><head><title>404 - Site Bulunamadı</title></head><body style='font-family:sans-serif;text-align:center;padding:50px;'><h1>404 - Site Bulunamadı</h1><p>\\"" + cleanHost + "\\" adresi için aktif bir JetKur sitesi bulunamadı.</p></body></html>",
        {
          status: 404,
          headers: { "Content-Type": "text/html; charset=utf-8", "X-Content-Type-Options": "nosniff" }
        }
      );
    }

    // 2. Normalize asset path inside immutable namespace (sites/<siteId>/v<version>/)
    let path = url.pathname;
    if (path === "/" || path === "" || path === "/index" || path === "/home") {
      path = "/index.html";
    }

    // Prevent path traversal
    if (path.includes("..") || path.includes("\\\\")) {
      return new Response("Bad Request: Invalid path", { status: 400 });
    }

    const rewrittenPath = "/" + route.artifactPrefix + path;
    const assetUrl = new URL(rewrittenPath, url.origin);

    // 3. Delegate to Cloudflare Workers Static Assets binding (env.ASSETS)
    const assetRequest = new Request(assetUrl.toString(), request);
    let response;
    try {
      response = await env.ASSETS.fetch(assetRequest);
    } catch (err) {
      return new Response("Internal Edge Error", { status: 500 });
    }

    // If subpage not found, attempt serving artifact's 404.html
    if (response.status === 404 && !path.startsWith("/assets/")) {
      const notFoundUrl = new URL("/" + route.artifactPrefix + "/404.html", url.origin);
      const notFoundRes = await env.ASSETS.fetch(new Request(notFoundUrl.toString(), request));
      if (notFoundRes.status === 200) {
        response = new Response(notFoundRes.body, {
          status: 404,
          headers: notFoundRes.headers
        });
      }
    }

    // 4. Inject security & deployment headers
    const newHeaders = new Headers(response.headers);
    newHeaders.set("X-Frame-Options", "SAMEORIGIN");
    newHeaders.set("X-Content-Type-Options", "nosniff");
    newHeaders.set("X-JetKur-Site-Id", route.siteId);
    newHeaders.set("X-JetKur-Version", String(route.version));

    // Cache-Control strategy
    const isImmutable = path.startsWith("/assets/") || path.endsWith(".css") || path.endsWith(".js") || path.endsWith(".webp");
    if (isImmutable) {
      newHeaders.set("Cache-Control", "public, max-age=31536000, immutable");
    } else {
      newHeaders.set("Cache-Control", "public, max-age=0, must-revalidate");
    }

    return new Response(response.body, {
      status: response.status,
      statusText: response.statusText,
      headers: newHeaders
    });
  }
};
`;
}
